version: '3'
services:
  brickd:
    build: ../lrpi-brickd
    container_name: brickd
    privileged: true
    image: "lushdigital/lrpi-brickd:latest"
    volumes:
      - "/etc/opt/lushroom:/etc/opt/lushroom"
    restart: always
  commands:
    build: ../lrpi-commands
    container_name: commands
    privileged: true
    links:
      - brickd
    depends_on:
      - brickd
    image: "lushdigital/lrpi-commands:latest"
    volumes:
      - "/etc/opt/lushroom:/etc/opt/lushroom"
    env_file: .env
    restart: always
  rclone:
    build: ../lrpi-rclone
    container_name: rclone
    privileged: true
    image: "lushdigital/lrpi-commands:latest"
    volumes:
       - /media/usb:/media/usb
    restart: always
  player:
    container_name: player
    build: ../lrpi-player
    image: "lushdigital/lrpi-player:latest"
    privileged: true
    links:
      - brickd
    depends_on:
      - brickd
    volumes:
       - /media/usb/tracks:/media/usb/tracks
       - /opt/vc
    command: python3 omx-player-service.py
    restart: always
